# ***************************************************************************************
# This is the User Defined Settings file which controls the complete execution
# Please see the Wiki for formatting details as setting descriptions.
#          https://github.com/daniel-fudge/DRL-Portfolio-Optimization/wiki
# ***************************************************************************************

# Stock settings
sp500:    SPY
tickers:  [SPY, AAP, ACN, ADBE, AFL, ALB, ALK, AOS, ATVI, AYI, MMM]
data_start:    2007-12-31
data_end:      2020-07-01
training_end:  2017-12-31
prediction_days: [1, 5, 21]

# LSTM Hyperparameters
embedding_days:  63
gradient_clipping:  5.0
